# Generated by Django 6.0.5 on 2026-05-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagingactivitydata',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='stagingactivitydata',
            name='validation_errors',
        ),
        migrations.AddField(
            model_name='stagingactivitydata',
            name='anomaly_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingactivitydata',
            name='category',
            field=models.CharField(blank=True, choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=10),
        ),
        migrations.AddField(
            model_name='stagingactivitydata',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stagingactivitydata',
            name='normalized_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stagingactivitydata',
            name='raw_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stagingactivitydata',
            name='status',
            field=models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('SUSPICIOUS', 'Suspicious'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='UNREVIEWED', max_length=20),
        ),
        migrations.AddField(
            model_name='stagingactivitydata',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
